title: 初代星・初代銀河研究会2025   
description: 初代星から生命へ
show_downloads: false
google_analytics: G-YBCR8KCM7R
theme: jekyll-theme-cayman
sass:
  style: compressed
#plugins:
#  - jekyll-sitemap
header_pages:
  - index.md
  #- registration.md
  - link.md
